#!/usr/bin/python3

import os, pprint
from sys import argv, exc_info

trace = 1
dirname, extname = os.curdir, '.py'

if len(argv) > 1: dirname = argv[1]
if len(argv) > 2: extname = argv[2]
if len(argv